-- CreateEnum
CREATE TYPE "EventInvitationTemplate" AS ENUM ('BIRTHDAY_CONFETTI', 'BIRTHDAY_ELEGANT', 'BIRTHDAY_NEON', 'WEDDING_IVORY', 'WEDDING_BOTANICAL', 'WEDDING_GOLD', 'BABY_SHOWER_TEDDY', 'BABY_SHOWER_CLOUDS', 'BABY_SHOWER_STORYBOOK', 'GRADUATION_CLASSIC', 'GRADUATION_MODERN', 'GRADUATION_GALA', 'CORPORATE_MINIMAL', 'CORPORATE_PREMIUM', 'CORPORATE_EXECUTIVE', 'PARTY_RETRO', 'PARTY_NEON', 'PARTY_LUXE', 'ENGAGEMENT_ROMANCE', 'ENGAGEMENT_GARDEN', 'ENGAGEMENT_ROSE_GOLD', 'FESTIVAL_VIBRANT', 'FESTIVAL_TRADITIONAL', 'FESTIVAL_MODERN', 'ANNIVERSARY_CLASSIC', 'ANNIVERSARY_GOLDEN', 'ANNIVERSARY_ROMANTIC', 'RECEPTION_ELEGANT', 'RECEPTION_CRYSTAL', 'RECEPTION_GRAND', 'PRODUCT_LAUNCH_TECH', 'PRODUCT_LAUNCH_MINIMAL', 'PRODUCT_LAUNCH_PREMIUM');

-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "invitationTemplate" "EventInvitationTemplate";
