import { Router } from 'express';
import { adminRouter } from '../modules/admin/admin.routes.js';
import { authRouter } from '../modules/auth/auth.routes.js';
import { categoryRouter } from '../modules/categories/category.routes.js';
import { eventRouter } from '../modules/events/event.routes.js';
import { healthRouter } from '../modules/health/health.routes.js';
import { vendorRouter } from '../modules/vendors/vendor.routes.js';
import { packageRouter } from '../modules/packages/package.routes.js';
import { quotationRequestRouter } from '../modules/quotationRequests/quotationRequest.routes.js';
import { bookingRouter } from '../modules/bookings/booking.routes.js';
import { notificationRouter } from '../modules/notifications/notification.routes.js';
import { budgetRouter } from '../modules/budgets/budget.routes.js';
import { eventTaskRouter } from '../modules/eventTasks/eventTask.routes.js';
import { guestRouter } from '../modules/guests/guest.routes.js';
import { invitationRouter } from '../modules/invitations/invitation.routes.js';

export const apiRouter = Router();

apiRouter.use('/health', healthRouter);
apiRouter.use('/auth', authRouter);
apiRouter.use('/events', eventRouter);
apiRouter.use('/vendors', vendorRouter);
apiRouter.use('/categories', categoryRouter);
apiRouter.use('/admin', adminRouter);
apiRouter.use('/packages', packageRouter);
apiRouter.use('/quotation-requests', quotationRequestRouter);
apiRouter.use('/bookings', bookingRouter);
apiRouter.use('/notifications', notificationRouter);
apiRouter.use('/budgets', budgetRouter);
apiRouter.use('/event-tasks', eventTaskRouter);
apiRouter.use('/guests', guestRouter);
apiRouter.use('/invitations', invitationRouter);
