import { GuestStatus, type PrismaClient } from '@prisma/client';
import { DEVELOPMENT_CUSTOMERS } from './constants.js';
import { getRequiredEventByNameAndOwner, getRequiredUserByEmail } from './helpers.js';

const DEVELOPMENT_GUESTS = [
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[0].email,
    eventName: 'Emma and Daniel Wedding',
    firstName: 'Sophia',
    lastName: 'Johnson',
    email: 'sophia.johnson@example.com',
    phone: '+94771110001',
    groupName: 'Bride Family',
    status: GuestStatus.CONFIRMED,
    partySize: 2,
    mealPreference: 'Non-vegetarian',
    dietaryRequirements: null,
    notes: 'Bride’s elder sister and spouse.',
    invitedAt: new Date('2026-06-15T08:00:00.000Z'),
    respondedAt: new Date('2026-06-16T12:20:00.000Z'),
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[0].email,
    eventName: 'Emma and Daniel Wedding',
    firstName: 'Nathan',
    lastName: 'Johnson',
    email: 'nathan.johnson@example.com',
    phone: '+94771110002',
    groupName: 'Bride Family',
    status: GuestStatus.CONFIRMED,
    partySize: 3,
    mealPreference: 'Mixed',
    dietaryRequirements: 'One vegetarian meal required.',
    notes: 'Bride’s cousin attending with family.',
    invitedAt: new Date('2026-06-15T08:00:00.000Z'),
    respondedAt: new Date('2026-06-18T09:10:00.000Z'),
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[0].email,
    eventName: 'Emma and Daniel Wedding',
    firstName: 'Isabella',
    lastName: 'Perera',
    email: 'isabella.perera@example.com',
    phone: '+94771110003',
    groupName: 'Close Friends',
    status: GuestStatus.MAYBE,
    partySize: 1,
    mealPreference: 'Vegetarian',
    dietaryRequirements: null,
    notes: 'Waiting for overseas travel confirmation.',
    invitedAt: new Date('2026-06-17T08:30:00.000Z'),
    respondedAt: new Date('2026-06-22T14:00:00.000Z'),
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[0].email,
    eventName: 'Emma and Daniel Wedding',
    firstName: 'Ethan',
    lastName: 'Fernando',
    email: 'ethan.fernando@example.com',
    phone: '+94771110004',
    groupName: 'Groom Friends',
    status: GuestStatus.INVITED,
    partySize: 2,
    mealPreference: null,
    dietaryRequirements: null,
    notes: null,
    invitedAt: new Date('2026-06-17T08:30:00.000Z'),
    respondedAt: null,
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[0].email,
    eventName: 'Emma and Daniel Wedding',
    firstName: 'Grace',
    lastName: 'Silva',
    email: 'grace.silva@example.com',
    phone: '+94771110005',
    groupName: 'University Friends',
    status: GuestStatus.DECLINED,
    partySize: 1,
    mealPreference: null,
    dietaryRequirements: null,
    notes: 'Unable to attend due to overseas studies.',
    invitedAt: new Date('2026-06-18T10:00:00.000Z'),
    respondedAt: new Date('2026-06-25T16:45:00.000Z'),
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[0].email,
    eventName: 'Emma and Daniel Wedding',
    firstName: 'Noah',
    lastName: 'Wijesinghe',
    email: 'noah.wijesinghe@example.com',
    phone: '+94771110006',
    groupName: 'Work Colleagues',
    status: GuestStatus.NOT_INVITED,
    partySize: 1,
    mealPreference: null,
    dietaryRequirements: null,
    notes: 'Invitation pending final guest-count review.',
    invitedAt: null,
    respondedAt: null,
  },

  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[1].email,
    eventName: 'NovaTech Annual Conference',
    firstName: 'Anika',
    lastName: 'Jayawardena',
    email: 'anika.jayawardena@novatech.example',
    phone: '+94772220001',
    groupName: 'Speakers',
    status: GuestStatus.CONFIRMED,
    partySize: 1,
    mealPreference: 'Vegetarian',
    dietaryRequirements: null,
    notes: 'Opening keynote speaker.',
    invitedAt: new Date('2026-06-10T07:30:00.000Z'),
    respondedAt: new Date('2026-06-11T10:00:00.000Z'),
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[1].email,
    eventName: 'NovaTech Annual Conference',
    firstName: 'Ravindu',
    lastName: 'Perera',
    email: 'ravindu.perera@novatech.example',
    phone: '+94772220002',
    groupName: 'Speakers',
    status: GuestStatus.CONFIRMED,
    partySize: 1,
    mealPreference: 'Non-vegetarian',
    dietaryRequirements: null,
    notes: 'Panel discussion participant.',
    invitedAt: new Date('2026-06-10T07:30:00.000Z'),
    respondedAt: new Date('2026-06-12T09:15:00.000Z'),
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[1].email,
    eventName: 'NovaTech Annual Conference',
    firstName: 'Mariam',
    lastName: 'Hassan',
    email: 'mariam.hassan@partner.example',
    phone: '+94772220003',
    groupName: 'Partners',
    status: GuestStatus.CONFIRMED,
    partySize: 2,
    mealPreference: 'Halal',
    dietaryRequirements: 'Halal meals required.',
    notes: 'Attending with a colleague.',
    invitedAt: new Date('2026-06-20T08:00:00.000Z'),
    respondedAt: new Date('2026-06-22T11:40:00.000Z'),
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[1].email,
    eventName: 'NovaTech Annual Conference',
    firstName: 'Kevin',
    lastName: 'De Silva',
    email: 'kevin.desilva@sponsor.example',
    phone: '+94772220004',
    groupName: 'Sponsors',
    status: GuestStatus.INVITED,
    partySize: 2,
    mealPreference: null,
    dietaryRequirements: null,
    notes: 'Awaiting sponsor-team attendee confirmation.',
    invitedAt: new Date('2026-06-24T09:00:00.000Z'),
    respondedAt: null,
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[1].email,
    eventName: 'NovaTech Annual Conference',
    firstName: 'Tharushi',
    lastName: 'Gunasekara',
    email: 'tharushi.gunasekara@novatech.example',
    phone: '+94772220005',
    groupName: 'Employees',
    status: GuestStatus.MAYBE,
    partySize: 1,
    mealPreference: 'Vegetarian',
    dietaryRequirements: null,
    notes: 'May have a client meeting on the same date.',
    invitedAt: new Date('2026-06-25T08:15:00.000Z'),
    respondedAt: new Date('2026-06-28T14:30:00.000Z'),
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[1].email,
    eventName: 'NovaTech Annual Conference',
    firstName: 'Liam',
    lastName: 'Rodrigo',
    email: 'liam.rodrigo@media.example',
    phone: '+94772220006',
    groupName: 'Media',
    status: GuestStatus.NOT_INVITED,
    partySize: 1,
    mealPreference: null,
    dietaryRequirements: null,
    notes: 'Media invitation pending communications approval.',
    invitedAt: null,
    respondedAt: null,
  },

  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[2].email,
    eventName: 'Olivia Birthday Celebration',
    firstName: 'Chloe',
    lastName: 'Fernando',
    email: 'chloe.fernando@example.com',
    phone: '+94773330001',
    groupName: 'Family',
    status: GuestStatus.CONFIRMED,
    partySize: 3,
    mealPreference: 'Mixed',
    dietaryRequirements: 'One child-friendly meal.',
    notes: 'Attending with spouse and child.',
    invitedAt: new Date('2026-07-05T09:00:00.000Z'),
    respondedAt: new Date('2026-07-06T12:30:00.000Z'),
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[2].email,
    eventName: 'Olivia Birthday Celebration',
    firstName: 'Ava',
    lastName: 'Peris',
    email: 'ava.peris@example.com',
    phone: '+94773330002',
    groupName: 'Close Friends',
    status: GuestStatus.CONFIRMED,
    partySize: 2,
    mealPreference: 'Vegetarian',
    dietaryRequirements: null,
    notes: null,
    invitedAt: new Date('2026-07-05T09:00:00.000Z'),
    respondedAt: new Date('2026-07-06T08:45:00.000Z'),
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[2].email,
    eventName: 'Olivia Birthday Celebration',
    firstName: 'Mason',
    lastName: 'Silva',
    email: 'mason.silva@example.com',
    phone: '+94773330003',
    groupName: 'Close Friends',
    status: GuestStatus.INVITED,
    partySize: 1,
    mealPreference: null,
    dietaryRequirements: null,
    notes: null,
    invitedAt: new Date('2026-07-07T10:00:00.000Z'),
    respondedAt: null,
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[2].email,
    eventName: 'Olivia Birthday Celebration',
    firstName: 'Zara',
    lastName: 'Rahman',
    email: 'zara.rahman@example.com',
    phone: '+94773330004',
    groupName: 'University Friends',
    status: GuestStatus.MAYBE,
    partySize: 2,
    mealPreference: 'Halal',
    dietaryRequirements: 'Halal meals required.',
    notes: 'Waiting to confirm travel from Colombo.',
    invitedAt: new Date('2026-07-07T10:00:00.000Z'),
    respondedAt: new Date('2026-07-09T13:20:00.000Z'),
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[2].email,
    eventName: 'Olivia Birthday Celebration',
    firstName: 'Lucas',
    lastName: 'Jayasinghe',
    email: 'lucas.jayasinghe@example.com',
    phone: '+94773330005',
    groupName: 'Work Friends',
    status: GuestStatus.DECLINED,
    partySize: 1,
    mealPreference: null,
    dietaryRequirements: null,
    notes: 'Unavailable due to work travel.',
    invitedAt: new Date('2026-07-08T08:30:00.000Z'),
    respondedAt: new Date('2026-07-10T15:10:00.000Z'),
  },
  {
    ownerEmail: DEVELOPMENT_CUSTOMERS[2].email,
    eventName: 'Olivia Birthday Celebration',
    firstName: 'Mia',
    lastName: 'Wickramasinghe',
    email: 'mia.wickramasinghe@example.com',
    phone: '+94773330006',
    groupName: 'Family Friends',
    status: GuestStatus.NOT_INVITED,
    partySize: 2,
    mealPreference: null,
    dietaryRequirements: null,
    notes: 'Pending final capacity confirmation.',
    invitedAt: null,
    respondedAt: null,
  },
] as const;

export const seedEventGuests = async (prisma: PrismaClient) => {
  let seededGuestCount = 0;

  for (const guestData of DEVELOPMENT_GUESTS) {
    const owner = await getRequiredUserByEmail(prisma, guestData.ownerEmail);

    const event = await getRequiredEventByNameAndOwner(prisma, guestData.eventName, owner.id);

    const existingGuest = await prisma.guest.findFirst({
      where: {
        eventId: event.id,
        email: guestData.email,
      },
    });

    const guestValues = {
      firstName: guestData.firstName,
      lastName: guestData.lastName,
      email: guestData.email,
      phone: guestData.phone,
      groupName: guestData.groupName,
      status: guestData.status,
      partySize: guestData.partySize,
      mealPreference: guestData.mealPreference,
      dietaryRequirements: guestData.dietaryRequirements,
      notes: guestData.notes,
      invitedAt: guestData.invitedAt,
      respondedAt: guestData.respondedAt,
    };

    if (existingGuest) {
      await prisma.guest.update({
        where: {
          id: existingGuest.id,
        },
        data: guestValues,
      });
    } else {
      await prisma.guest.create({
        data: {
          eventId: event.id,
          ...guestValues,
        },
      });
    }

    seededGuestCount += 1;
  }

  console.log(`${seededGuestCount} event guests seeded successfully.`);
};
